#
# docker build -t spark-master -f Dockerfile-spark-master .
#
FROM spark-base:latest


# ENV
ENV SPARK_VERSION=spark-2.4.3-bin-hadoop2.7

ENV SPARK_MASTER_PORT=7077
ENV SPARK_MASTER_WEBUI_PORT=8001
ENV SPARK_DRIVER_MEMORY=4g
ENV SPARK_WORKER_CORES=2
ENV SPARK_WORKER_MEMORY=1g

EXPOSE 7077 8001

# 启动
CMD /spark/$SPARK_VERSION/bin/spark-class org.apache.spark.deploy.master.Master --port $SPARK_MASTER_PORT --webui-port $SPARK_MASTER_WEBUI_PORT