#
# docker build -t spark -f Dockerfile-spark .
#

FROM ubuntu:xenial

COPY ./common/sources.list /etc/apt/sources.list

RUN apt-get update --fix-missing  -y && apt-get update -y

# 环境安装
WORKDIR /opt 
RUN apt-get install -y openjdk-8-jdk apt-transport-https wget python3 python3-pip \
	&& ln -s /usr/bin/python3 /usr/bin/python

# ENV
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/