version: "3.4"
# (https://docs.docker.com/compose/compose-file/#extension-fields)

x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: '12m'
    max-file: '5'

services:
  spark-master:
    image: spark-master:latest
    container_name: spark-master
    ports:
      - "8001:8080"
      - "7077:7077"
    restart: always
    logging: *default-logging
    networks:
      - "mynet1"

  spark-worker1:
    image: spark-worker:latest
    container_name: spark-worker1
    ports:
      - "8002:8080"
    restart: always
    logging: *default-logging
    depends_on:
      - spark-master
    networks:
      - "mynet1"

  spark-worker2:
    image: spark-worker:latest
    container_name: spark-worker2
    ports:
      - "8003:8080"
    restart: always
    logging: *default-logging
    depends_on:
      - spark-master
    networks:
      - "mynet1"

networks:
  mynet1:
    driver: bridge