version: "3.4"
# (https://docs.docker.com/compose/compose-file/#extension-fields)

x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: '12m'
    max-file: '5'

x-deploy:
  &default-deploy
  restart_policy:
    condition: any
    delay: 10s
  replicas: 1

services:
  spark-master:
    image: spark:latest
    container_name: spark-master
    ports:
      - "81:8080"
      - "82:7077"
    deploy: *default-deploy
    logging: *default-logging

  spark-worker1:
    image: worker:latest
    container_name: spark-worker1
    ports:
      - "91:8080"
    deploy: *default-deploy
    logging: *default-logging
    depends_on:
      - spark-master

  spark-worker2:
    image: worker:latest
    container_name: spark-worker2
    ports:
      - "92:8080"
    deploy: *default-deploy
    logging: *default-logging
    depends_on:
      - spark-master