version: "3.4"
# (https://docs.docker.com/compose/compose-file/#extension-fields)

x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: '12m'
    max-file: '5'

x-deploy:
  &default-deploy
  restart_policy:
    condition: any
    delay: 10s
  replicas: 1

services:
  spark-master:
    image: spark-master:latest
    container_name: spark-master
    ports:
      - "8001:8001"
      - "7077:7077"
    deploy: *default-deploy
    logging: *default-logging

  spark-worker:
    image: spark-worker:latest
    container_name: spark-worker
    ports:
      - "8002:8002"
    deploy: *default-deploy
    logging: *default-logging
    depends_on:
      - spark-master
